name: "Terraform DB Pipeline"

on:
  push:
    branches:
      - main

env:
  REGION_DEFAULT: us-east-1

jobs:
  deploy:
    name: Deploying Infrastructure DB in AWS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify Terraform Files
        run: |
          if [ -z "$(find . -type f -name '*.tf')" ]; then
            echo "No Terraform files found in the repository."
            exit 1
          fi

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ env.REGION_DEFAULT }}

      - name: Terraform Format
        working-directory: ./terraform       
        run: terraform fmt -check

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init
      
      - name: Terraform Validate
        working-directory: ./terraform
        run: terraform validate -no-color

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan -no-color -input=false -out=tfplan

      - name: Terraform Apply
        working-directory: ./terraform
        if: success() && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve -input=false
